### ISSUE TITLE
VB20 - filter the beneficiary using phone and landline 

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/voluntar-backend#116]
when a new request is added the system should be able to identify if the beneficiary already exists in the system.

**Comment by serghei-rubailo** [comment]
Hi!
Could you please approve that I understand task correctly.

When POST request to /api/beneficiary is sent then system has to check: if beneficiary with the same "phone" AND "landline" phone is already exists in the database.
Or we have to check: if beneficiary with the same "phone" OR "landline" is already exists in the database. 

I would prefer OR option, because if beneficiary is created only with phone number and after user will try to enter phone and landline for next beneficiary, then AND option will not return error that beneficiary already exists in the system.

And if the beneficiary exists we have to return an error: "Beneficiary with [phone|landline] <phone number> already exists in the system".

Thank you.

**Comment by johnsmithm** [comment]
it just phone and just landline, you can update the /api/beneficiary/filters/1/5.

how it works https://www.figma.com/proto/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=565%3A188&scaling=min-zoom
