### ISSUE TITLE
VB-2: Update get volunteers by filters

### ISSUE THREAD

**Issue by alexciornii** [code4moldova/voluntar-backend#85]
It is necessary to add the ability to filter users by the following fields:
- phone
- zone
- role

**Comment by serghei-rubailo** [comment]
Hi! Suppose this issue should be done after next pull request will be in the master #100 .
As I see Volunteer model is changed in the #100 and there are no phone, zone, role fields for Volunteer.
Please assign to me when it will be possible to add changes.

**Comment by johnsmithm** [comment]
here we need something more complicated for the filters because we need to look for the same string in 3 different fields: first and last name + phone. one idea is to merge all three fields:  last_name + first_name + phone and look in the concatenated field (will  need aggregate), or we can use the OR operator, example [here](https://stackoverflow.com/questions/8189702/mongodb-using-an-or-clause-in-mongoengine).
